name: CI
on:
    pull_request:
        branches: ['*']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - name: Saved result path
              id: SaveResultPath
              run: |
                  project=''

                  for type in module product; do
                      if [ -d "./coverage/$type" ]; then
                          for dir in `ls ./coverage/$type`; do
                              if [ -f "./coverage/$type/$dir/coverage-summary.json" ]; then
                                  project+="$dir, ./coverage/$type/$dir/coverage-summary.json\n"
                              fi
                          done
                      fi
                  done

                  echo "project=$project" >> $GITHUB_OUTPUT
        outputs:
            project: ${{steps.SaveResultPath.outputs.project}}
                     
  
    comment_test:
      runs-on: ubuntu-latest
      needs: [test]
      steps:
        - name: Test2
          run: echo "js_${{needs.test.outputs.project}}"

    comment:
      runs-on: ubuntu-latest
      needs: [test]
      if : ${{success() && needs.test.outputs.project != null }}
      steps:
          - uses: actions/checkout@v2
          - name: Jest Coverage Comment
            uses: MishaKav/jest-coverage-comment@main
            with:
              github-token: ${{github.token}}
              multiple-files: ${{needs.test.outputs.project}}

