name: CI
on:
    pull_request:
        branches: ['*']

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            
            - name: Saved result path
              id: SaveResultPath
              run: |
                  project=''

                  for type in module product; do
                      if [ -d "./coverage/$type" ]; then
                          for dir in `ls ./coverage/$type`; do
                              if [ -f "./coverage/$type/$dir/coverage-summary.json" ]; then
                                  project+="$dir, ./coverage/$type/$dir/coverage-summary.json\n"
                              fi
                          done
                      fi
                  done

                  echo -e "$project" > project.temp

            - name: Read file contents
              id: read_file
              uses: andstor/file-reader-action@v1
              with:
                path: "project.temp"

            - name: Jest Coverage Comment
              uses: MishaKav/jest-coverage-comment@main
              with:
                 github-token: ${{github.token}}
                 multiple-files: ${{steps.read_file.outputs.contents}} 
